export const userConstants = {
  SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE',

  CHANGE_PASSWORD_REQUEST: 'USERS_CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'USERS_CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'USERS_CHANGE_PASSWORD_FAILURE',

  REMEMBERME_CEHCKED: 'USERS_REMEMBER_ME',
  REMEMBERME_UNCEHCKED: 'USERS_NOT_REMEMBER_ME',

  STORE_USER_DETAILS: 'USER_DETAILS_STORE',
  REMOVE_USER_DETAILS: 'USER_DETAILS_REMOVE',
  UPDATE_USER_DETAILS: 'USER_DETAILS_UPDATE',

  STORE_DOC_DETAILS: 'DOC_DETAILS_STORE',
  REMOVE_DOC_DETAILS: 'DOC_DETAILS_REMOVE',

  STORE_MEDICINE: 'STORE_MEDICINE',
  REMOVE_MEDICINE: 'REMOVE_MEDICINE',

  STORE_ADVICE: 'STORE_ADVICE',
  REMOVE_ADVICE: 'REMOVE_ADVICE',

  STORE_FOLLOW_UP: 'STORE_FOLLOW_UP',
  REMOVE_FOLLOW_UP: 'REMOVE_FOLLOW_UP',

  STORE_CHIEF_COMPLAINT: 'STORE_CHIEF_COMPLAINT',
  REMOVE_CHIEF_COMPLAINT: 'REMOVE_CHIEF_COMPLAINT',

  STORE_HISTORY: 'STORE_CHIEF_HISTORY',
  REMOVE_HISTORY: 'REMOVE_CHIEF_HISTORY',

  STORE_DIAGNOSIS: 'STORE_DIAGNOSIS',
  REMOVE_DIAGNOSIS: 'REMOVE_DIAGNOSIS',

  STORE_ON_EXAMINATION: 'STORE_ON_EXAMINATION',
  REMOVE_ON_EXAMINATION: 'REMOVE_ON_EXAMINATION',

  STORE_INVESTIGATION: 'STORE_INVESTIGATION',
  REMOVE_INVESTIGATION: 'REMOVE_INVESTIGATION',

  REMOVE_PRESCTIPTION_ALL: 'REMOVE_PRESCTIPTION_ALL',
};
