/* eslint-disable prettier/prettier */
export const Medicine = [
  {
    genericName: 'Nicotinamide',
    medicines: [
      {
        type: 'Tab',
        brand_name: 'Xinc B',
        company_name: 'Eskayef Bangladesh LTD, Mirpur',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 15,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Xinc B',
        company_name: 'Eskayef Bangladesh LTD., Tongi',
        suggetions: [
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: 'spoon',
            day: 14,
          },
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 14,
          },

          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Bicozin',
        company_name: 'Square Pharmaceuticals LTD., Pabna',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 15,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5',
            day: 14,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Bicozin',
        company_name: 'Square Formulation LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Fil Wel Kids',
        company_name: 'Square Pharmaceuticals LTD., Pabna',
        suggetions: [
          {
            dose1: '2 spoon',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Momvit',
        company_name: 'Beximco Pharmaceutical LTD',
        suggetions: [
          {
            dose1: '',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Pep Plus',
        company_name: 'Orion Pharma LTD.',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 15,
          },
          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5 spoon',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
          {
            dose1: '2 spoon',
            dose2: '',
            dose3: '2 spoon',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 15,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'V Plex',
        company_name: 'Acme Laboratories LTD.',
        suggetions: [
          {
            dose1: '10 drops',
            dose2: '',
            dose3: '',
            day: 15,
          },
          {
            dose1: '15 drops',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '6 drops',
            dose2: '',
            dose3: '',
            day: 15,
          },
          {
            dose1: '15 spoon',
            dose2: '',
            dose3: '15 spoon',
            day: 14,
          },
          {
            dose1: '5 drops',
            dose2: '',
            dose3: '',
            day: 90,
          },
          {
            dose1: '10 drops',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '20 spoon',
            dose2: '',
            dose3: '20 spoon',
            day: 14,
          },
          {
            dose1: '10 drops',
            dose2: '',
            dose3: '',
            day: 30,
          },
          {
            dose1: '6 drops',
            dose2: '',
            dose3: '',
            day: 180,
          },
          {
            dose1: '15 drops',
            dose2: '',
            dose3: '15 drops',
            day: 14,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Bicozin-I',
        company_name: 'Square pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 30,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 30,
          },
        ],
      },
      {
        type: 'Drop',
        brand_name: 'Cytonic Drop',
        company_name: 'ACI LTD.',
        suggetions: [],
      },
      {
        type: 'Drop',
        brand_name: 'Catrix Drop',
        company_name: 'Incepta Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Drop',
        brand_name: 'Catnil Drop',
        company_name: 'Acme Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Drop',
        brand_name: 'Catavit Drop',
        company_name: 'Apex Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Drop',
        brand_name: 'Adenovit Drop',
        company_name: 'Drug International LTD.',
        suggetions: [],
      },
      {
        type: 'Drop',
        brand_name: 'Vitaphakol Drop',
        company_name: 'Novartis (Bangladesh) LTD.',
        suggetions: [],
      },
      {
        type: 'Drop',
        brand_name: 'Vitamide Drop',
        company_name: 'Goco Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Drop',
        brand_name: 'Vitalens Drop',
        company_name: 'General Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Drop',
        brand_name: 'Vitafol Drop',
        company_name: 'Popular Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Drop',
        brand_name: 'Ractovit Drop',
        company_name: 'Ibn-Sina Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Drop',
        brand_name: 'Phacovit Drop',
        company_name: 'Aristopharma LTD.',
        suggetions: [],
      },
      {
        type: 'Drop',
        brand_name: 'AC-Fol Drop',
        company_name: 'Nipa Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Drop',
        brand_name: 'Ancys Drop',
        company_name: 'Monicopharma LTD.',
        suggetions: [],
      },
      {
        type: 'Drop',
        brand_name: 'Mediphakol Drop',
        company_name: 'Rema Drug Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Drop',
        brand_name: 'Lensovit Drop',
        company_name: 'Beximco pharmaceuticals LTD.',
        suggetions: [],
      },
    ],
  },
  {
    genericName: 'Pyridoxine Hydrochloride',
    medicines: [
      {
        type: 'Tab',
        brand_name: 'Xinc B',
        company_name: 'Eskayef Bangladesh LTD. Mirpur',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 15,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Xinc B',
        company_name: 'Eskayef Bangladesh LTD. Tongi',
        suggetions: [
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 14,
          },
          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'B126',
        company_name: 'Popular Pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 'To be continue',
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Bicozin',
        company_name: 'Square Pharmaceuticals LTD. Pabna',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 15,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Bicozin',
        company_name: 'Square Formulations LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Acliz PLUS',
        company_name: 'Aristopharma LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '1',
            dose3: '1',
            day: 15,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Filwel Kids',
        company_name: 'Square Pharmaceuticals LTD. Pabna',
        suggetions: [
          {
            dose1: '2 spoon',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Neobion',
        company_name: 'aristopharma LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 90,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 60,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Momvit',
        company_name: 'Beximco Pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Pep PLUS',
        company_name: 'Orion Pharma LTD.',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 15,
          },
          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5 spoon',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
          {
            dose1: '2 spoon',
            dose2: '',
            dose3: '2 spoon',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 15,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'V Plex',
        company_name: 'Acme Laboratories LTD.',
        suggetions: [
          {
            dose1: '10 drops',
            dose2: '',
            dose3: '',
            day: 15,
          },
          {
            dose1: '15 drops',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '6 drops',
            dose2: '',
            dose3: '',
            day: 15,
          },

          {
            dose1: '5 drops',
            dose2: '',
            dose3: '',
            day: 90,
          },
          {
            dose1: '10 drops',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '20 drops',
            dose2: '',
            dose3: '20 drops',
            day: 14,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Bicozin-I',
        company_name: 'Square Pharmaceutical LTD. Pabna',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 30,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: 'spoon',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'bost',
        company_name: 'General Pharmaceutical LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 60,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Dicliz PLus 20 Extended Releas',
        company_name: 'Aristopharma LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 7,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'G Vitamin B6',
        company_name: 'Gonoshasthaya pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'B Six 25 mg',
        company_name: 'Peoples Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Sixvit 20 mg',
        company_name: 'Beacon Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Pyroxin 100 mg/ml',
        company_name: 'Gaco Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Pyroxin 25 mg',
        company_name: 'Gaco Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Pyrovit 20 mg',
        company_name: 'Pharmadesh Labboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Pyrol 25 mg',
        company_name: 'Jayson Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Pyridoxine 25 mg',
        company_name: 'Essential Drugs Company LTD.',
        suggetions: [],
      },
    ],
  },
  {
    genericName: 'Riboflavin',
    medicines: [
      {
        type: 'Tab',
        brand_name: 'Xinc B',
        company_name: 'Eskayef Bangladesh LTD. Mirpur',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 15,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Xinc B',
        company_name: 'Eskayef Bangladesh LTD. Tongi',
        suggetions: [
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 14,
          },
          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Bicozin',
        company_name: 'Square Pharmaceuticals LTD. Pabna',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 15,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Bicozin',
        company_name: 'Square Formulations LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Vitalgin',
        company_name: 'Ibn Sina Pharmaceuticals LTD. Pabna',
        suggetions: [
          {
            dose1: '3 spoon',
            dose2: '3 spoon',
            dose3: '3 spoon',
            day: 15,
          },
          {
            dose1: '3 spoon',
            dose2: '3 spoon',
            dose3: '3 spoon',
            day: 30,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Fil Wel Kids',
        company_name: 'Square Pharmaceuticals LTD., Pabna',
        suggetions: [
          {
            dose1: '2 spoon',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Momvit',
        company_name: 'Beximco Pharmaceuticals LTD',
        suggetions: [
          {
            dose1: '',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'tab',
        brand_name: 'FilWel Teen Hr',
        company_name: 'Square Pharmaceuticals LTD., Pabna',
        suggetions: [
          {
            dose1: '',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Pep Plus',
        company_name: 'Orion Pharma LTD.',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 15,
          },
          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5 spoon',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
          {
            dose1: '2 spoon',
            dose2: '',
            dose3: '2 spoon',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 15,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'V Plex',
        company_name: 'Acme Laboratories LTD.',
        suggetions: [
          {
            dose1: '10 drops',
            dose2: '',
            dose3: '',
            day: 15,
          },
          {
            dose1: '15 drops',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '6 drops',
            dose2: '',
            dose3: '',
            day: 15,
          },
          {
            dose1: '15 spoon',
            dose2: '',
            dose3: '15 spoon',
            day: 14,
          },
          {
            dose1: '5 drops',
            dose2: '',
            dose3: '',
            day: 90,
          },
          {
            dose1: '10 drops',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '20 spoon',
            dose2: '',
            dose3: '20 spoon',
            day: 14,
          },
          {
            dose1: '10 drops',
            dose2: '',
            dose3: '',
            day: 30,
          },
          {
            dose1: '6 drops',
            dose2: '',
            dose3: '',
            day: 180,
          },
          {
            dose1: '15 drops',
            dose2: '',
            dose3: '15 drops',
            day: 14,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Bicozin-I',
        company_name: 'Square pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 30,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Filwel Teen Hm',
        company_name: 'Healthcare pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Bextram Teen HR',
        company_name: 'Beximco pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Bextram Teen HM',
        company_name: 'Beximco pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'G Vitamin B2',
        company_name: 'Gonoshasthaya pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Rivin 5 mg',
        company_name: 'Supreme pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Ribozen 5 mg',
        company_name: 'Zenith pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Ribovit 5 mg',
        company_name: 'Aexim pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Ribotab 5 mg',
        company_name: 'Ziska pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboson 5 mg',
        company_name: 'Jayson pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Ribosina 5 mg',
        company_name: 'Ibn sina pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboseem 5 mg',
        company_name: 'Seema pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Ribomin 5 mg',
        company_name: 'Ad-Din pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'Monicopharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'Essential Drugs Company LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'Bristol Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: `Doctor's Chemical LTD.`,
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'Cipla LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'Chemist Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'Indo Bangla Pharmaceutical.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'Pharmadesh Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'United Chemicals & Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavin 5 mg',
        company_name: 'Opsonin Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavin 5 mg',
        company_name: 'Hudson Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'Bristol Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'Biogene Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'Medicon Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'Rephco Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'Reliance Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'Concord Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Riboflavine 5 mg',
        company_name: 'Amico Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Ribolex 5 mg',
        company_name: 'Globe Pharmaceuticals LTD.',
        suggetions: [],
      },
    ],
  },
  {
    genericName: 'Vitamin B1',
    medicines: [
      {
        type: 'Tab',
        brand_name: 'Xinc B',
        company_name: 'Eskayef Bangladesh LTD. Mirpur',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 15,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Xinc B',
        company_name: 'Eskayef Bangladesh LTD. Tongi',
        suggetions: [
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 14,
          },
          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Bicozin',
        company_name: 'Square Pharmaceuticals LTD. Pabna',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 15,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Bicozin',
        company_name: 'Square Formulations LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Vitalgin',
        company_name: 'Ibn Sina Pharmaceuticals LTD. Pabna',
        suggetions: [
          {
            dose1: '3 spoon',
            dose2: '3 spoon',
            dose3: '3 spoon',
            day: 15,
          },
          {
            dose1: '3 spoon',
            dose2: '3 spoon',
            dose3: '3 spoon',
            day: 30,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Fil Wel Kids',
        company_name: 'Square Pharmaceuticals LTD., Pabna',
        suggetions: [
          {
            dose1: '2 spoon',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Vitabion',
        company_name: 'Incepta Pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 60,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
          {
            dose1: '1',
            dose2: '1',
            dose3: '1',
            day: 90,
          },
          {
            dose1: '',
            dose2: '1',
            dose3: '',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Neobion',
        company_name: 'aristopharma LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 90,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 60,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Pep Plus',
        company_name: 'Orion Pharma LTD.',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 15,
          },
          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5 spoon',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
          {
            dose1: '2 spoon',
            dose2: '',
            dose3: '2 spoon',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 15,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'V Plex',
        company_name: 'Acme Laboratories LTD.',
        suggetions: [
          {
            dose1: '10 drops',
            dose2: '',
            dose3: '',
            day: 15,
          },
          {
            dose1: '15 drops',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '6 drops',
            dose2: '',
            dose3: '',
            day: 15,
          },
          {
            dose1: '15 spoon',
            dose2: '',
            dose3: '15 spoon',
            day: 14,
          },
          {
            dose1: '5 drops',
            dose2: '',
            dose3: '',
            day: 90,
          },
          {
            dose1: '10 drops',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '20 spoon',
            dose2: '',
            dose3: '20 spoon',
            day: 14,
          },
          {
            dose1: '10 drops',
            dose2: '',
            dose3: '',
            day: 30,
          },
          {
            dose1: '6 drops',
            dose2: '',
            dose3: '',
            day: 180,
          },
          {
            dose1: '15 drops',
            dose2: '',
            dose3: '15 drops',
            day: 14,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Bicozin-I',
        company_name: 'Square pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 30,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'V3N',
        company_name: 'NIPRO JMI pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neurobest',
        company_name: 'Renata LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 90,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'TPC',
        company_name: 'Acme Laboratories LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '1',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Neucos B',
        company_name: 'Radiant Pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '1',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Bost',
        company_name: 'General Pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 60,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Tribion',
        company_name: 'Globe Pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: ' Getbion',
        company_name: 'Get Well  LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: ' ethibion',
        company_name: 'Ethical Drug LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: ' eon',
        company_name: 'Everest Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: '3-B',
        company_name: 'ACP Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: '3-B',
        company_name: 'APC Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'D- Vital',
        company_name: `Doctor's Chemical LTD.`,
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: '3 Bion',
        company_name: 'Julphar Bangladesh LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Debion',
        company_name: 'Delta Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Debion',
        company_name: 'Delta Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Cypath',
        company_name: 'Tecno Drugs LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Cyano-B',
        company_name: 'Orbit Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Combomin',
        company_name: 'Ad-Din Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Centobion',
        company_name: 'Centeon Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'B-Vitacom',
        company_name: 'Centeon Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Bost',
        company_name: 'General Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Bost',
        company_name: 'General Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Bionic',
        company_name: 'Pharmasia LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Bionic',
        company_name: 'Pharmasia LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Big B',
        company_name: 'Amico Laboratoris LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Berin Plus',
        company_name: 'GlaxoSmithKline',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'B126',
        company_name: 'Popular Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'B 3',
        company_name: 'Bristol Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Axovit',
        company_name: 'Doctor TIMS Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'VT-3',
        company_name: 'Decent Pharma Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'V-Nerve',
        company_name: 'MonicoPharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'VN',
        company_name: 'Reliance Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Vitalex b',
        company_name: 'Reliance Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Vitabion',
        company_name: 'Incepta Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'V-Nerve',
        company_name: 'MonicoPharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Virobion',
        company_name: 'virgo Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Viotin',
        company_name: 'Salton Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Vigor',
        company_name: 'Hallmark Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Unibion',
        company_name: 'Desh Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Tribion',
        company_name: 'Globe Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'TRI-B',
        company_name: 'The White Horse pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Tpc',
        company_name: 'Acme Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Ti Ediplex',
        company_name: 'Edruc LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Temvit-N',
        company_name: 'Team Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Astra-N',
        company_name: 'Astra Biopharceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Supra-B',
        company_name: 'Drug International LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Supra-B',
        company_name: 'Drug International LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Solbion ',
        company_name: 'Eskayef Bangladesh LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Solbion ',
        company_name: 'Eskayef Bangladesh LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Serobion ',
        company_name: 'Leon Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Serobion ',
        company_name: 'Leon Pharmaceutical LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Asibion',
        company_name: 'Asiatic Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Asibion IM',
        company_name: 'Asiatic Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'SB-Neurec',
        company_name: 'Sunman-Birdem pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Reoplex Forte',
        company_name: 'Rephco Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Renovit',
        company_name: 'Health Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Renerv Plus',
        company_name: 'Gaco Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Renep',
        company_name: 'Alco Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Rejubion',
        company_name: 'Beacon Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Rejubion',
        company_name: 'Beacon Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Aristovit',
        company_name: 'Beximco Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Rebion',
        company_name: 'Rephco Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Rebion',
        company_name: 'Rephco Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Aristovit',
        company_name: 'Beximco Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Povital',
        company_name: 'ACI LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Povital',
        company_name: 'ACI LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Pacibion',
        company_name: 'Pacific Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'OST',
        company_name: 'Central Pharmaceuticals LTD.(CPL)',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Orgabion',
        company_name: 'Organic Health Care',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Ocuguard',
        company_name: 'Gaco Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'N-Vit',
        company_name: 'MST Pharma',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Nuvista',
        company_name: 'Nuvista Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Nuropa',
        company_name: 'Nipa Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Nuroguard',
        company_name: 'Guardian Healthcare LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Nurobix Plus',
        company_name: 'Chemist Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Nurobix Plus',
        company_name: 'Chemist Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Nugesic',
        company_name: 'Orion Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Nugesic',
        company_name: 'Orion Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Nopath',
        company_name: 'Amulet Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Nins',
        company_name: 'Benhum Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Nevrona',
        company_name: 'One Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neuvital',
        company_name: 'Unimed Unihealth MFG. LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neuvit Plus',
        company_name: 'United Chemicals & Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neutos',
        company_name: 'Union Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neurotonic',
        company_name: 'Globex Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Neurotonic',
        company_name: 'Globex Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neuroson',
        company_name: 'Hudson Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neuronorm',
        company_name: 'Mundipharma (BD) Pvt. LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neuromate',
        company_name: 'Labaid Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neurofol',
        company_name: 'Crystal Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neurodol',
        company_name: 'Rangs Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neurocone',
        company_name: 'Pharmik Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neurocon',
        company_name: 'Novelta Bestway Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neurocare',
        company_name: 'Beximco Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'NeuroBest',
        company_name: 'Renata LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Neuro-B',
        company_name: 'Square Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neuro-B',
        company_name: 'Square Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neuroaid',
        company_name: 'Novo Healthcare & Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Neuro Prax',
        company_name: 'Concord Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neuro Prax',
        company_name: 'Concord Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neurex-B',
        company_name: 'Silva Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neurep',
        company_name: 'Biopharma Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neuremed',
        company_name: 'MedRx Life Science LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Neuralgin',
        company_name: 'Ibn Sina Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neural',
        company_name: 'Innova Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Neubin',
        company_name: 'Ziska Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neubin',
        company_name: 'Ziska Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neu-3',
        company_name: 'Cosmic Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Nervo-b',
        company_name: 'Apex Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Nerviplex',
        company_name: 'Jayson Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Nerviplex',
        company_name: 'Jayson Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Nervin',
        company_name: 'Jayson Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Nerva',
        company_name: 'Pharmadesh Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Nerbo',
        company_name: 'Sharif Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Neobion',
        company_name: 'AristoPharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Neobion',
        company_name: 'AristoPharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Nenvitn',
        company_name: 'Euro Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Myolin',
        company_name: 'Beximco Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Myobion',
        company_name: 'Kumudini Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Myelin',
        company_name: 'Opsonin Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Myelin',
        company_name: 'Opsonin Pharma LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Miovit',
        company_name: 'Somatec Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Medibion',
        company_name: 'Medicon Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Tab',
        brand_name: 'Kvit-N',
        company_name: 'Kemiko Pharmaceuticals LTD.',
        suggetions: [],
      },
      {
        type: 'Inj',
        brand_name: 'Kvit-N',
        company_name: 'Kemiko Pharmaceuticals LTD.',
        suggetions: [],
      },
    ],
  },
  {
    genericName: 'Zinc',
    medicines: [
      {
        type: 'Tab',
        brand_name: 'Xinc B',
        company_name: 'Eskayef Bangladesh LTD. Mirpur',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 15,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Xinc B',
        company_name: 'Eskayef Bangladesh LTD., Tongi',
        suggetions: [
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: 'spoon',
            day: 14,
          },
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 14,
          },

          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Bicozin',
        company_name: 'Square Pharmaceuticals LTD., Pabna',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 15,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5',
            day: 14,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Bicozin',
        company_name: 'Square Formulation LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Pep 20',
        company_name: 'Orion Pharma LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Xinc 10mg/5ml',
        company_name: 'Eskayef Bangladesh LTD. Mirpur',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Pep 20mg/5ml',
        company_name: 'Orion Pharma LTD.',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 15,
          },
          {
            dose1: '0.25 spoon',
            dose2: '',
            dose3: '0.25 spoon',
            day: 15,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Xinc 20 mg',
        company_name: 'Eskayef Bangladesh LTD. Mirpur',
        suggetions: [
          {
            dose1: '1',
            dose2: '1',
            dose3: '',
            day: 30,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 15,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Ipec PLUS',
        company_name: 'Aristopharma LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
          {
            dose1: '',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Tab',
        brand_name: 'Momvit',
        company_name: 'Beximco Pharmaceuticals LTD',
        suggetions: [
          {
            dose1: '',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'tab',
        brand_name: 'FilWel Teen Hr',
        company_name: 'Square Pharmaceuticals LTD., Pabna',
        suggetions: [
          {
            dose1: '',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Bicozin-I',
        company_name: 'Square pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 30,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 30,
          },
        ],
      },
      {
        type: 'Surp',
        brand_name: 'Pep 4mg/5ml  4.05mg/5ml',
        company_name: 'Orion Pharma LTD.',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'tab',
        brand_name: 'Folic Z',
        company_name: 'Opsonin Pharma LTD',
        suggetions: [
          {
            dose1: '',
            dose2: '',
            dose3: '1',
            day: 30,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '',
            day: 'To be continue',
          },
        ],
      },
      {
        type: 'tab',
        brand_name: 'Pep PLus 10',
        company_name: 'Orion Pharma LTD',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: '15',
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Pep Plus',
        company_name: 'Orion Pharma LTD.',
        suggetions: [
          {
            dose1: '0.5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 15,
          },
          {
            dose1: '1.5 spoon',
            dose2: '',
            dose3: '1.5 spoon',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 14,
          },
          {
            dose1: '2 spoon',
            dose2: '',
            dose3: '2 spoon',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '',
            day: 14,
          },
          {
            dose1: '1 spoon',
            dose2: '',
            dose3: '1 spoon',
            day: 15,
          },
        ],
      },
      {
        type: 'tab',
        brand_name: 'FilWel Teen Hm',
        company_name: 'Healthcare  Pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'tab',
        brand_name: 'Bextram Teen HR',
        company_name: 'Beximco  Pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Ziton 10 mg/5 ml',
        company_name: 'Drug International LTD.',
        suggetions: [
          {
            dose1: '0,5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Zis DS 20 mg/5 ml',
        company_name: 'Acme Laboratories LTD.',
        suggetions: [
          {
            dose1: '0,5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Cap',
        brand_name: 'IPEC Super',
        company_name: 'Aristopharma LTD.',
        suggetions: [
          {
            dose1: '1',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'tab',
        brand_name: 'Bextram Teen HM',
        company_name: 'Beximco  Pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '',
            dose2: '',
            dose3: '1',
            day: 30,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Mazic 10 mg/5 ml',
        company_name: 'Renata LTD.',
        suggetions: [
          {
            dose1: '0,5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Syrp',
        brand_name: 'Zikid 10 mg/5 ml',
        company_name: 'Globe Pharmaceuticals LTD.',
        suggetions: [
          {
            dose1: '0,5 spoon',
            dose2: '',
            dose3: '0.5 spoon',
            day: 14,
          },
        ],
      },
      {
        type: 'Cap',
        brand_name: 'Fivita',
        company_name: 'Biopharma laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Syrp',
        brand_name: 'Fizovit',
        company_name: 'Doctor`s chemical Works LTD.',
        suggetions: [],
      },
      {
        type: 'Syrp',
        brand_name: 'Fiziplex',
        company_name: 'Acme Laboratories LTD.',
        suggetions: [],
      },
      {
        type: 'Cap',
        brand_name: 'Feviz',
        company_name: 'Popular Pharmaceuticals LTD.',
        suggetions: [],
      },
    ],
  },
];
